import type { Metadata } from "next";
import { Lustria, Source_Serif_4 } from "next/font/google";
import Toolbar from "@/components/toolbar";
import Footer from "@/components/footer";
import "./globals.css";

const lustria = Lustria({
  variable: "--font-lustria",
  subsets: ["latin"],
  weight: "400",
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lustria.variable} ${sourceSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toolbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
