import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import Toolbar from "@/components/toolbar";
import Footer from "@/components/footer";
import "./globals.css";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ubuntu.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toolbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
